baseURL : "http://andrewcharman.tech/"
languageCode : "en-us"
title : "Andrew Charman"
theme : "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-138535910-3

# Enable Disqus forum
#disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # copyright
  copyright: © 2020 Copyright.

  # background image of the landing page
  background: "assets/images/background1.jpg"

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # testing section/widgets
  enableExperiences: true
  sections : true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  #customMenus:
  #- name: Notes
  #  url: https://hossainnotes.netlify.app/docs/example/

  # some information about you
  author:
    name: "Andrew Charman"
    nickname: "Andrew"
    image: "assets/images/avatar.jpg"
    
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "andrew.charman@hotmail.com"
      #phone: "+0123456789"
    
    # a summary of what you do
    summary:
     - I am a brave leader
     - I interested in learning new technologies